package cn.iocoder.yudao.module.linbang.constants;

public interface LinbangRiskConstants {

    String STATUS_ENABLE = "ENABLE";
    String STATUS_DISABLE = "DISABLE";

    String RESTRICT_STATUS_ACTIVE = "ACTIVE";
    String RESTRICT_STATUS_RELEASED = "RELEASED";

    String RESTRICT_TYPE_PUBLISH = "PUBLISH";
    String RESTRICT_TYPE_ACCEPT = "ACCEPT";
    String RESTRICT_TYPE_PROMOTE = "PROMOTE";

    String RISK_STATUS_PENDING = "PENDING";
    String RISK_STATUS_PROCESSING = "PROCESSING";
    String RISK_STATUS_FINISHED = "FINISHED";

    String RISK_DISPOSE_STATUS_PENDING = "PENDING";
    String RISK_DISPOSE_STATUS_CONFIRMED = "CONFIRMED";
    String RISK_DISPOSE_STATUS_RELEASED = "RELEASED";

    String RISK_DISPOSE_ACTION_CONFIRM = "CONFIRM_VIOLATION";
    String RISK_DISPOSE_ACTION_RELEASE = "RELEASE_FALSE_POSITIVE";
    String RISK_DISPOSE_ACTION_FREEZE = "FREEZE_FUNDS";
    String RISK_DISPOSE_ACTION_UNFREEZE = "UNFREEZE_FUNDS";
    String RISK_DISPOSE_ACTION_BLACKLIST = "ADD_BLACKLIST";
    String RISK_DISPOSE_ACTION_BAN_USER = "BAN_USER";
    String RISK_DISPOSE_ACTION_RESTRICT_PUBLISH = "RESTRICT_PUBLISH";
    String RISK_DISPOSE_ACTION_RESTRICT_ACCEPT = "RESTRICT_ACCEPT";

    String RISK_TYPE_CANCEL_LIMIT = "ORDER_CANCEL_LIMIT";
    String RISK_TYPE_SELF_DEAL = "SELF_DEAL";
    String RISK_TYPE_RELATED_ACCOUNT = "RELATED_ACCOUNT";
    String RISK_TYPE_SWIPE_ORDER = "SWIPE_ORDER";
    String RISK_TYPE_SENSITIVE_CONTENT = "SENSITIVE_CONTENT";

    String RISK_LEVEL_LOW = "LOW";
    String RISK_LEVEL_MEDIUM = "MEDIUM";
    String RISK_LEVEL_HIGH = "HIGH";

    String DEPOSIT_PAY_STATUS_NOT_REQUIRED = "NOT_REQUIRED";
    String DEPOSIT_PAY_STATUS_UNPAID = "UNPAID";
    String DEPOSIT_PAY_STATUS_PAID = "PAID";

    String FROZEN_STATUS_ACTIVE = "ACTIVE";
    String FROZEN_STATUS_RELEASED = "RELEASED";

    String SCENE_MESSAGE = "MESSAGE";
    String SCENE_COMMENT = "COMMENT";
    String SCENE_COMPLAINT = "COMPLAINT";
    String SCENE_APPEAL = "APPEAL";
    String SCENE_PROMOTE = "PROMOTE";
    String SCENE_NICKNAME = "NICKNAME";
    String SCENE_ORDER_PUBLISH = "ORDER_PUBLISH";

    String SENSITIVE_STRATEGY_BLOCK = "BLOCK";
    String SENSITIVE_STRATEGY_REPLACE = "REPLACE";
    String SENSITIVE_STRATEGY_REVIEW = "REVIEW";
    String SENSITIVE_STRATEGY_ALLOW_LOG = "ALLOW_LOG";

    String PROMOTE_STATUS_DRAFT = "DRAFT";
    String PROMOTE_STATUS_PENDING_SYSTEM_AUDIT = "PENDING_SYSTEM_AUDIT";
    String PROMOTE_STATUS_PENDING_MANUAL_AUDIT = "PENDING_MANUAL_AUDIT";
    String PROMOTE_STATUS_APPROVED = "APPROVED";
    String PROMOTE_STATUS_REJECTED = "REJECTED";
    String PROMOTE_STATUS_OFFLINE = "OFFLINE";

    String PROMOTE_AUDIT_TYPE_SYSTEM = "SYSTEM";
    String PROMOTE_AUDIT_TYPE_MANUAL = "MANUAL";

    String PROMOTE_APPEAL_STATUS_PENDING = "PENDING";
    String PROMOTE_APPEAL_STATUS_APPROVED = "APPROVED";
    String PROMOTE_APPEAL_STATUS_REJECTED = "REJECTED";

    String PENALTY_ACTION_DEMOTE = "DEMOTE";
    String PENALTY_ACTION_RESTRICT_PROMOTE = "RESTRICT_PROMOTE";
    String PENALTY_ACTION_DISABLE_PROMOTER = "DISABLE_PROMOTER";
    String PENALTY_ACTION_SCORE = "SCORE";
}
