package cn.iocoder.yudao.module.linbang.constants;

import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

public interface MessageCenterConstants {

    String CHANNEL_APP_POPUP = "APP_POPUP";
    String CHANNEL_WECHAT_MP_TEMPLATE = "WECHAT_MP_TEMPLATE";
    String CHANNEL_SMS = "SMS";
    String CHANNEL_APP_VOICE = "APP_VOICE";

    String CATEGORY_SYSTEM = "SYSTEM";
    String CATEGORY_FINANCE = "FINANCE";
    String CATEGORY_ORDER = "ORDER";
    String CATEGORY_COMPLIANCE = "COMPLIANCE";
    String CATEGORY_DISPUTE = "DISPUTE";
    String CATEGORY_MARKETING = "MARKETING";
    String CATEGORY_MEETING_NOTICE = "MEETING_NOTICE";
    String CATEGORY_SUPERIOR_INSTRUCTION = "SUPERIOR_INSTRUCTION";

    String READ_STATUS_UNREAD = "UNREAD";
    String READ_STATUS_READ = "READ";

    String CAMPAIGN_SOURCE_USER_DIRECTED = "USER_DIRECTED";
    String CAMPAIGN_SOURCE_ADMIN_DIRECTED = "ADMIN_DIRECTED";
    String CAMPAIGN_SOURCE_SYSTEM_TRIGGER = "SYSTEM_TRIGGER";
    String CAMPAIGN_SOURCE_AD = "AD";

    String CAMPAIGN_AUDIT_PENDING = "PENDING";
    String CAMPAIGN_AUDIT_APPROVED = "APPROVED";
    String CAMPAIGN_AUDIT_REJECTED = "REJECTED";
    String CAMPAIGN_AUDIT_CANCELLED = "CANCELLED";

    String TARGET_MODE_FULL_PLATFORM = "FULL_PLATFORM";
    String TARGET_MODE_JURISDICTION = "JURISDICTION";
    String TARGET_MODE_CUSTOM_FILTER = "CUSTOM_FILTER";

    String EXECUTE_STATUS_PENDING = "PENDING";
    String EXECUTE_STATUS_PROCESSING = "PROCESSING";
    String EXECUTE_STATUS_SUCCESS = "SUCCESS";
    String EXECUTE_STATUS_PARTIAL_FAILED = "PARTIAL_FAILED";
    String EXECUTE_STATUS_FAILED = "FAILED";
    String EXECUTE_STATUS_CANCELLED = "CANCELLED";

    String REF_TYPE_TEMPLATE = "TEMPLATE";
    String REF_TYPE_CAMPAIGN = "CAMPAIGN";

    String SCENE_SYSTEM_NOTICE = "SYSTEM_NOTICE";
    String SCENE_FINANCE_PAYMENT_SUCCESS = "FINANCE_PAYMENT_SUCCESS";
    String SCENE_FINANCE_REFUND_SUCCESS = "FINANCE_REFUND_SUCCESS";
    String SCENE_FINANCE_WITHDRAW_AUDIT = "FINANCE_WITHDRAW_AUDIT";
    String SCENE_FINANCE_WITHDRAW_SUCCESS = "FINANCE_WITHDRAW_SUCCESS";
    String SCENE_FINANCE_COMMISSION_SETTLED = "FINANCE_COMMISSION_SETTLED";
    String SCENE_ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED";
    String SCENE_QUALIFICATION_EXPIRE_REMINDER = "QUALIFICATION_EXPIRE_REMINDER";
    String SCENE_QUALIFICATION_EXPIRE_DISABLE = "QUALIFICATION_EXPIRE_DISABLE";
    String SCENE_DISPUTE_CREATED = "DISPUTE_CREATED";
    String SCENE_DISPUTE_RESULT = "DISPUTE_RESULT";
    String SCENE_VERIFY_SUCCESS = "VERIFY_SUCCESS";
    String SCENE_VERIFY_EXCEPTION = "VERIFY_EXCEPTION";
    String SCENE_REMINDER_TRIGGER = "REMINDER_TRIGGER";
    String SCENE_MARKETING_BROADCAST = "MARKETING_BROADCAST";
    String SCENE_MEETING_NOTICE = "MEETING_NOTICE";
    String SCENE_SUPERIOR_INSTRUCTION = "SUPERIOR_INSTRUCTION";

    String BIZ_TYPE_MARKETING = "MARKETING";
    String BIZ_TYPE_QUALIFICATION_EXPIRY = "QUALIFICATION_EXPIRY";
    String BIZ_TYPE_USER_REMINDER = "USER_REMINDER";
    String BIZ_TYPE_PARTNER_INSTRUCTION = "PARTNER_INSTRUCTION";
    String BIZ_TYPE_PARTNER_MEETING = "PARTNER_MEETING";

    Set<String> FINANCE_SCENES = Collections.unmodifiableSet(new LinkedHashSet<>(Arrays.asList(
            SCENE_FINANCE_PAYMENT_SUCCESS,
            SCENE_FINANCE_REFUND_SUCCESS,
            SCENE_FINANCE_WITHDRAW_AUDIT,
            SCENE_FINANCE_WITHDRAW_SUCCESS,
            SCENE_FINANCE_COMMISSION_SETTLED
    )));

    Map<String, String> LEGACY_TEMPLATE_SCENE_MAPPING = Collections.unmodifiableMap(new LinkedHashMap<String, String>() {{
        put("lb_role_apply_audited", SCENE_SYSTEM_NOTICE);
        put("lb_merchant_entry_audited", SCENE_SYSTEM_NOTICE);
        put("lb_price_report_audited", SCENE_SYSTEM_NOTICE);
        put("lb_refund_audited", SCENE_FINANCE_REFUND_SUCCESS);
        put("lb_withdraw_audited", SCENE_FINANCE_WITHDRAW_AUDIT);
        put("lb_qualification_expire_reminder", SCENE_QUALIFICATION_EXPIRE_REMINDER);
        put("lb_qualification_expire_disable", SCENE_QUALIFICATION_EXPIRE_DISABLE);
        put("lb_merchant_accept_enabled", SCENE_SYSTEM_NOTICE);
        put("lb_bind_bank_card_required", SCENE_SYSTEM_NOTICE);
        put("lb_cert_exemption_audited", SCENE_SYSTEM_NOTICE);
        put("lb_special_cert_audited", SCENE_SYSTEM_NOTICE);
    }});
}
