### /pay/order/submit 提交支付订单【aggregate 聚合支付】
POST {{appApi}}/pay/order/submit
Content-Type: application/json
Authorization: Bearer {{appToken}}
tenant-id: {{appTenantId}}

{
  "id": 174,
  "channelCode": "aggregate"
}
